version: '3.8'

services:
  web:
    build: .
    container_name: app
    ports:
      - "${PORT}:${FAST_API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
